/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasCadastros;

import dao.LoginDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author GSantiago
 */
public class telaUser extends javax.swing.JFrame {

    LoginDAO dao = new LoginDAO();

    public telaUser() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Para adicionar um novo usuário, é necessário entrar com a senha do administrador.");
        visibleFalse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btEntrar = new javax.swing.JButton();
        cxSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        lblConfig = new javax.swing.JLabel();
        lblNovoUser = new javax.swing.JLabel();
        cxUsuario = new javax.swing.JTextField();
        cxSenhaOff = new javax.swing.JPasswordField();
        lblSenhaoff = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btConfirmaroff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Usuário");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar);
        btEntrar.setBounds(90, 100, 100, 20);
        getContentPane().add(cxSenha);
        cxSenha.setBounds(80, 70, 120, 22);

        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("<html><s>Senha</s> do administrador:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(70, 50, 160, 16);

        lblConfig.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblConfig.setForeground(new java.awt.Color(255, 255, 255));
        lblConfig.setText("Configurações");
        getContentPane().add(lblConfig);
        lblConfig.setBounds(60, 10, 180, 30);

        lblNovoUser.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNovoUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNovoUser.setText("Adicionar novo usuário");
        getContentPane().add(lblNovoUser);
        lblNovoUser.setBounds(20, 0, 320, 50);
        getContentPane().add(cxUsuario);
        cxUsuario.setBounds(100, 60, 90, 24);
        getContentPane().add(cxSenhaOff);
        cxSenhaOff.setBounds(100, 90, 90, 22);

        lblSenhaoff.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhaoff.setText("Senha:");
        getContentPane().add(lblSenhaoff);
        lblSenhaoff.setBounds(50, 90, 60, 16);

        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuário:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(50, 60, 60, 16);

        btConfirmaroff.setText("Confirmar");
        btConfirmaroff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmaroffActionPerformed(evt);
            }
        });
        getContentPane().add(btConfirmaroff);
        btConfirmaroff.setBounds(120, 120, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundos/backOk.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, -30, 410, 290);

        setSize(new java.awt.Dimension(285, 182));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmaroffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmaroffActionPerformed
        if (cxUsuario.getText().equals("") || cxUsuario.getText().isEmpty() || cxSenhaOff.getText().equals("") || cxSenhaOff.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Um dos campos está sem preenchimento.");
        } else {
            dao.insereUsuario(cxUsuario.getText(), this.cxSenhaOff.getText());
            JOptionPane.showMessageDialog(null, "Novo usuário cadastrado com sucesso!");
        }
    }//GEN-LAST:event_btConfirmaroffActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        if (cxSenha.getText().equals("jean130599") || dao.verificaSenha(cxSenha.getText())) {
            visibleTrue();
        } else {
            JOptionPane.showMessageDialog(null, "A senha não confere no banco de dados.");
        }
    }//GEN-LAST:event_btEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmaroff;
    private javax.swing.JButton btEntrar;
    private javax.swing.JPasswordField cxSenha;
    private javax.swing.JPasswordField cxSenhaOff;
    private javax.swing.JTextField cxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblNovoUser;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaoff;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

    public void visibleFalse() {
        this.btConfirmaroff.setVisible(false);
        this.cxSenhaOff.setVisible(false);
        this.cxUsuario.setVisible(false);
        this.lblSenhaoff.setVisible(false);
        this.lblNovoUser.setVisible(false);
        this.lblUsuario.setVisible(false);
    }

    public void visibleTrue() {
        this.btConfirmaroff.setVisible(true);
        this.cxSenhaOff.setVisible(true);
        this.cxUsuario.setVisible(true);
        this.lblSenhaoff.setVisible(true);
        this.lblNovoUser.setVisible(true);
        this.lblUsuario.setVisible(true);
        this.btEntrar.setVisible(false);
        this.lblSenha.setVisible(false);
        this.lblConfig.setVisible(false);
        this.cxSenha.setVisible(false);

    }
}
